### ISSUE TITLE
SEMRush Error: Wrong Pages In Sitemap

### ISSUE THREAD

**Issue by atweedie** [webuyanybike/webuyanybike#14]
The author pages are showing in the site map despite them being canonical to the blog index. This is throwing an error in the SEMRush auditing system.

**Comment by atweedie** [comment]
https://www.webuyanybike.co.uk/blog/authors/jo-butler/
https://www.webuyanybike.co.uk/blog/authors/webuyanybike/

**Comment by glcheetham** [comment]
Confirmed fixed on develop branch
